name: AllTests-Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Test
      run: cd tests && cmake -S . -B build && cmake --build build && cd build && ctest